function figure_Charge(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 15-Mar-2017 09:15:27

% Create figure
figure1 = figure('Name','Charge, U = 1.1','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.107955010224949 0.775 0.815]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'Color',[1 0 0],'DisplayName','N = 30');

% Create plot
plot(X2,Y2,'Parent',axes1,...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794],...
    'DisplayName','N = 40');

% Create xlabel
xlabel('Jt / N');

% Create ylabel
ylabel('Charge');

% Create plot
plot(X3,Y3,'Parent',axes1,'Color',[0 0 1],'DisplayName','N = 20');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.731694828469022 0.745739604635317 0.14900153609831 0.124062713019768]);

